// Razas más comunes en Argentina, agrupadas por especie.

const RAZAS_POR_ESPECIE = {
  PERRO: [
    "DESCONOZCO",
    "MESTIZO",
    "AKITA",
    "AMERICAN STAFFORDSHIRE TERRIER",
    "BASSET HOUND",
    "LABRADOR RETRIEVER",
    "GOLDEN RETRIEVER",
    "PASTOR ALEMÁN",
    "CANICHE",
    "BULLDOG INGLÉS",
    "BULLDOG FRANCÉS",
    "BEAGLE",
    "COLLIE",
    "HUSKY SIBERIANO",
    "ROTTWEILER",
    "BOXER",
    "DÁLMATA",
    "YORKSHIRE TERRIER",
    "CHIHUAHUA",
    "SALCHICHA",
    "COCKER SPANIEL",
    "DOBERMAN",
    "FILA BRASILEIRO",
    "GALGO",
    "PITBULL",
    "PINSCHER MINIATURA",
    "BORDER COLLIE",
    "MASTÍN NAPOLITANO",
    "OVEJERO BELGA MALINOIS",
    "PERRO PILA ARGENTINO",
    "POINTER / BRACO",
    "PUG / CARLINO",
    "SAMOYEDO",
    "SHAR PEI",
    "SCHNAUZER",
    "BULL TERRIER",
    "MALTÉS",
    "SHIH TZU",
    "POMERANIA",
    "CHOW CHOW",
    "GRAN DANÉS",
    "SAN BERNARDO",
    "WEIMARANER",
    "BICHÓN FRISÉ",
    "LHASA APSO",
    "JACK RUSSELL TERRIER",
    "VIZSLA",
    "DOGO ARGENTINO",
    "DOGO CANARIO",
    "CIMARRÓN URUGUAYO",
    "SETTER IRLANDÉS",
    "OTRO",
  ],
  GATO: [
    "MESTIZO",
    "SIAMÉS",
    "PERSA",
    "ANGORA",
    "MAINE COON",
    "BRITISH SHORTHAIR",
    "RAGDOLL",
    "BENGALÍ",
    "SPHYNX",
    "AZUL RUSO",
    "ABISINIO",
    "SCOTTISH FOLD",
    "BURMÉS",
    "DEVON REX",
    "HIMALAYO",
    "OTRO",
  ],
  AVE: [
    "CANARIO",
    "COTORRA",
    "LORO HABLADOR",
    "CACATÚA",
    "AGAPORNIS",
    "NINFA (COCKATIEL)",
    "DIAMANTE",
    "CARDENAL",
    "PALOMA",
    "PERDIZ",
    "OTRO",
  ],
  CONEJO: [
    "MESTIZO",
    "ANGORA",
    "REX",
    "BELIER",
    "GIGANTE DE FLANDES",
    "ENANO HOLANDÉS",
    "LIONHEAD",
    "MINI REX",
    "CALIFORNIANO",
    "OTRO",
  ],
  OTRO: [
    "HAMSTER",
    "COBAYO / GUINEA PIG",
    "TORTUGA",
    "IGUANA",
    "HURÓN",
    "CHINCHILLA",
    "OTRO",
  ],
};

// Array plano para validaciones isIn() y enum de Mongoose
const RAZAS = Object.values(RAZAS_POR_ESPECIE).flat();

module.exports = {
  RAZAS,
  RAZAS_POR_ESPECIE,
};
